server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Reverse-proxy: /api/... va al backend por la red interna
    location /api/ {
        proxy_pass http://backend:8000/;
    }
}